// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUIVz86Pxqv9oggdgO7CPdmfLUMY-DRxo',
    appId: '1:769143430529:web:21bbb885eb151a778f5c80',
    messagingSenderId: '769143430529',
    projectId: 'localgroc-8aba2',
    authDomain: 'localgroc-8aba2.firebaseapp.com',
    storageBucket: 'localgroc-8aba2.firebasestorage.app',
    measurementId: 'G-ETM34MXRP8',
    databaseURL: 'https://localgroc-8aba2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAj66ax7aGuwur9WzWXNHVnIAyzovjdgc',
    appId: '1:769143430529:android:5da98738bfdd53cb8f5c80',
    messagingSenderId: '769143430529',
    projectId: 'localgroc-8aba2',
    storageBucket: 'localgroc-8aba2.firebasestorage.app',
    databaseURL: 'https://localgroc-8aba2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCdKm_ikqiTnDrebnebXGgNotfq-MuFSY',
    appId: '1:769143430529:ios:ac781177a4abaf928f5c80',
    messagingSenderId: '769143430529',
    projectId: 'localgroc-8aba2',
    storageBucket: 'localgroc-8aba2.firebasestorage.app',
    iosBundleId: 'com.example.localgroceries',
    databaseURL: 'https://localgroc-8aba2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCdKm_ikqiTnDrebnebXGgNotfq-MuFSY',
    appId: '1:769143430529:ios:ac781177a4abaf928f5c80',
    messagingSenderId: '769143430529',
    projectId: 'localgroc-8aba2',
    storageBucket: 'localgroc-8aba2.firebasestorage.app',
    iosBundleId: 'com.example.localgroceries',
    databaseURL: 'https://localgroc-8aba2-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUIVz86Pxqv9oggdgO7CPdmfLUMY-DRxo',
    appId: '1:769143430529:web:97cf12ff91f6cf1d8f5c80',
    messagingSenderId: '769143430529',
    projectId: 'localgroc-8aba2',
    authDomain: 'localgroc-8aba2.firebaseapp.com',
    storageBucket: 'localgroc-8aba2.firebasestorage.app',
    measurementId: 'G-C38YXH4J6H',
    databaseURL: 'https://localgroc-8aba2-default-rtdb.firebaseio.com',
  );
}
